#!/bin/bash
# Automated Android Environment Setup Script
# Generated by IDEaz

set -e

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

echo "Starting environment setup..."

# 0. Prerequisites
if ! command_exists wget || ! command_exists unzip; then
    echo "Installing prerequisites (wget, unzip)..."
    if command_exists apt-get; then
        sudo apt-get update
        sudo apt-get install -y wget unzip
    elif command_exists yum; then
        sudo yum install -y wget unzip
    elif command_exists apk; then
        sudo apk add wget unzip
    fi
fi

# 1. Java Setup (JDK 17)
if ! command_exists java; then
    echo "Java not found. Installing OpenJDK 17..."
    if command_exists apt-get; then
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
    elif command_exists yum; then
        sudo yum install -y java-17-openjdk
    elif command_exists apk; then
        sudo apk add openjdk17
    else
        echo "Error: Package manager not found. Please install JDK 17 manually."
        exit 1
    fi
else
    echo "Java is already installed."
fi

# Verify Java version (rough check)
java -version

# 2. Android SDK Setup
export ANDROID_HOME="$HOME/Android/sdk"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools"

if [ ! -d "$ANDROID_HOME" ]; then
    echo "Android SDK not found. Installing..."
    mkdir -p "$ANDROID_HOME/cmdline-tools"

    # Download Command Line Tools
    CMD_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
    wget -q "$CMD_TOOLS_URL" -O android_tools.zip
    unzip -q android_tools.zip -d "$ANDROID_HOME/cmdline-tools"
    rm android_tools.zip

    # Move to correct structure: cmdline-tools/latest
    mv "$ANDROID_HOME/cmdline-tools/cmdline-tools" "$ANDROID_HOME/cmdline-tools/latest"

    # Install basic SDK packages
    yes | sdkmanager --licenses
    sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
else
    echo "Android SDK directory exists."
fi

# 3. Write environment variables to .bashrc if not present
if [ -f "$HOME/.bashrc" ]; then
    if ! grep -q "ANDROID_HOME" "$HOME/.bashrc"; then
        echo "Adding environment variables to .bashrc..."
        echo '' >> "$HOME/.bashrc"
        echo 'export ANDROID_HOME=$HOME/Android/sdk' >> "$HOME/.bashrc"
        echo 'export ANDROID_SDK_ROOT=$ANDROID_HOME' >> "$HOME/.bashrc"
        echo 'export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools' >> "$HOME/.bashrc"
    fi
fi

echo "Environment setup complete."