name: Kaggle Experiment 001

on:
  push:
    branches: [main]
    paths:
      - '.kaggle-run'
  workflow_dispatch:

permissions: read-all

jobs:
  kaggle:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Centralized by HereLiesAz/workflows"
