# selected-action: pr-labeler
name: Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    uses: HereLiesAz/workflows/.github/workflows/pr-labeler.yml@3047ba321b6712f1b28c22907bb10bb78bdc4662 # main
