#!/usr/bin/env python3
"""Generate the Worker's webhook event-consumer map from the central registry.

The Cloudflare Worker forwards a repository webhook to gateway.yml only when some
registered workflow could consume it. Every forwarded event costs one gateway run,
and most webhook traffic (workflow_run, release, create, ...) has no consumer at all.

The map is ``{repository_id: {"repository": full_name, "events": [webhook event names]}}``
and mirrors how scripts/dispatch_request.py routes an event:

* only manifest entries whose status is ``active`` are routed, so only those count;
* a workflow's original ``on:`` trigger names are the events it consumes;
* a ``pull_request`` webhook also satisfies a ``pull_request_target`` trigger
  (GitHub never delivers a ``pull_request_target`` webhook);
* ``workflow_call`` and ``schedule`` are not webhooks (schedules are routed by
  dispatch_schedule.py). ``workflow_dispatch`` IS a webhook: GitHub delivers one when a
  workflow is run by hand in the target repository, and the gateway routes it, so it is kept;
* every registered repository consumes ``push``, because a push to its default
  branch that changes its workflow setup requests a re-sync
  (``_request_sync_if_setup_changed``), even when no active workflow uses push.

Branch, path and action filters are deliberately NOT applied here: the gateway still
makes the exact routing decision. The map only drops events no workflow could match.

Usage:
  python scripts/generate_event_consumers.py          # rewrite worker/src/event-consumers.js
  python scripts/generate_event_consumers.py --check  # fail if the committed module is stale
  python scripts/generate_event_consumers.py --list   # print every forwarded (repository, event)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Callable

from ruamel.yaml import YAML

ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = "worker/src/event-consumers.js"
ALWAYS_FORWARDED = ("push",)
NON_WEBHOOK_TRIGGERS = frozenset({"workflow_call", "schedule"})
TRIGGER_TO_WEBHOOK = {"pull_request_target": "pull_request"}
_DATA_START = "export const EVENT_CONSUMERS = "
_HEADER = (
    "// GENERATED by scripts/generate_event_consumers.py from registry/*/manifest.json. Do not edit.\n"
    "// Maps repository_id -> webhook event names that some active registered workflow consumes.\n"
    "// The Worker drops every other event before it can start a gateway run.\n"
    "// Regenerate: python scripts/generate_event_consumers.py\n"
)


def trigger_names(source_text: str) -> list[str]:
    doc = YAML(typ="safe").load(source_text) or {}
    if not isinstance(doc, dict):
        raise ValueError("workflow source is not a YAML mapping")
    on_value = doc.get("on")
    if isinstance(on_value, str):
        return [on_value]
    if isinstance(on_value, list):
        return [str(item) for item in on_value]
    if isinstance(on_value, dict):
        return [str(key) for key in on_value]
    return []


def webhook_events_for_triggers(triggers: list[str]) -> set[str]:
    events: set[str] = set()
    for trigger in triggers:
        if trigger in NON_WEBHOOK_TRIGGERS:
            continue
        events.add(TRIGGER_TO_WEBHOOK.get(trigger, trigger))
    return events


def repository_events(manifest: dict, read_source: Callable[[str], str]) -> list[str]:
    """Webhook events a registered repository consumes, given its manifest."""
    events: set[str] = set(ALWAYS_FORWARDED)
    for source_path, entry in sorted((manifest.get("workflows") or {}).items()):
        if not isinstance(entry, dict) or entry.get("status") != "active":
            continue
        registry_source = str(entry.get("registry_source") or "")
        if not registry_source:
            raise RuntimeError(f"Active workflow {source_path} has no registry_source")
        events |= webhook_events_for_triggers(trigger_names(read_source(registry_source)))
    return sorted(events)


def repository_entry(manifest: dict, read_source: Callable[[str], str]) -> tuple[str, dict]:
    repo = manifest.get("repository") or {}
    repository_id = str(repo.get("id") or "")
    if not repository_id:
        raise RuntimeError("Registry manifest has no repository.id")
    return repository_id, {
        "repository": str(repo.get("full_name") or ""),
        "events": repository_events(manifest, read_source),
    }


def build_consumer_map(root: Path = ROOT) -> dict[str, dict]:
    def read_local(registry_source: str) -> str:
        path = (root / registry_source).resolve()
        if root.resolve() not in path.parents or not path.is_file():
            raise RuntimeError(f"Registered workflow source is missing: {registry_source}")
        return path.read_text(encoding="utf-8")

    consumers: dict[str, dict] = {}
    for manifest_file in sorted((root / "registry").glob("*/manifest.json")):
        manifest = json.loads(manifest_file.read_text(encoding="utf-8"))
        if not isinstance(manifest, dict) or not (manifest.get("repository") or {}).get("id"):
            continue
        repository_id, entry = repository_entry(manifest, read_local)
        consumers[repository_id] = entry
    return consumers


def render_module(consumers: dict[str, dict]) -> str:
    ordered = {key: consumers[key] for key in sorted(consumers, key=lambda k: (len(k), k))}
    return _HEADER + _DATA_START + json.dumps(ordered, indent=2) + ";\n"


def parse_module(text: str) -> dict[str, dict]:
    start = text.index(_DATA_START) + len(_DATA_START)
    return json.loads(text[start:].rstrip().rstrip(";"))


def forwarded_pairs(consumers: dict[str, dict]) -> list[tuple[str, str]]:
    return sorted(
        (entry["repository"], event)
        for entry in consumers.values()
        for event in entry["events"]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="fail when the committed module is stale")
    parser.add_argument("--list", action="store_true", help="print every forwarded (repository, event) pair")
    args = parser.parse_args()

    consumers = build_consumer_map()
    rendered = render_module(consumers)
    module = ROOT / MODULE_PATH

    if args.list:
        for repository, event in forwarded_pairs(consumers):
            print(f"{repository}\t{event}")
        return 0
    if args.check:
        current = module.read_text(encoding="utf-8") if module.is_file() else ""
        if current != rendered:
            print(
                f"::error::{MODULE_PATH} is stale relative to registry/. "
                "Run: python scripts/generate_event_consumers.py",
                file=sys.stderr,
            )
            return 1
        print(f"{MODULE_PATH} is current ({len(consumers)} repositories, {len(forwarded_pairs(consumers))} pairs)")
        return 0
    module.write_text(rendered, encoding="utf-8")
    print(f"Wrote {MODULE_PATH} ({len(consumers)} repositories, {len(forwarded_pairs(consumers))} pairs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
